#!/usr/bin/env php
<?php
if (!defined("APP_ROOT")) {
    define("APP_ROOT", realpath(__DIR__ . "/../../../../"));
}
require_once(APP_ROOT . "/bootstrap.php");
use Zend\Stdlib\ConsoleHelper;
$begin = microtime(true);
echo "PSR2ifying... \n";
$pathsToPSR2 = [
    APP_ROOT . "/src/Models/Base",
    APP_ROOT . "/src/Models",
    APP_ROOT . "/src/Controllers/Base",
    APP_ROOT . "/src/Controllers",
    APP_ROOT . "/src/Services/Base",
    APP_ROOT . "/src/Services",
    APP_ROOT . "/src/*.php",
    APP_ROOT . "/tests/Api/Generated",
    APP_ROOT . "/tests/Models/Generated",
    APP_ROOT . "/public/index.php",
    APP_ROOT . "/vendor/segura/appcore",
    APP_ROOT . "/vendor/segura/zenderator",
    APP_ROOT . "/vendor/segura/libscmapi",
    APP_ROOT . "/vendor/segura/libschengen",
    APP_ROOT . "/vendor/segura/libapi",
    APP_ROOT . "/vendor/segura/libhorizon",
];

function psr2ify($pathToPSR2)
{
    ob_start();
    $begin = microtime(true);
    exec(APP_ROOT . "/vendor/bin/phpcbf --standard=PSR2 --ignore=*/vendor {$pathToPSR2}");
    $time = microtime(true) - $begin;
    echo " [" . ConsoleHelper::COLOR_GREEN . "Complete" . ConsoleHelper::COLOR_RESET . " in " . number_format($time, 2) . "]\n";
    echo ob_get_clean();
}

echo "AppRoot: " . APP_ROOT . "\n";

foreach ($pathsToPSR2 as $pathToPSR2) {
    echo " > {$pathToPSR2} ... ";
    if (file_exists($pathToPSR2)) {
        psr2ify($pathToPSR2);
    } else {
        echo " [" . ConsoleHelper::COLOR_RED . "Skipping" . ConsoleHelper::COLOR_RESET . ", files or directory does not exist.\n";
    }
}

$time = microtime(true) - $begin;
echo "[ALL DONE]";
echo " [Complete in " . number_format($time, 2) . "]\n";
