#!/usr/bin/env php
<?php

$rootOfApp = __DIR__ . "/../../../../";

require_once($rootOfApp . "/bootstrap.php");

$scope = APP_CORE_NAME;

$databaseConfigs = $scope::Container()->get("DatabaseConfig");

$zenderator = new \Zenderator\Zenderator(
    $rootOfApp,
    $databaseConfigs
);
$sdkOutputPath = isset($argv[1]) ? $argv[1] : APP_ROOT . "/vendor/segura/lib" . strtolower(APP_NAME) . "/";

$zenderator->purgeSDK($sdkOutputPath)
    ->checkGitSDK($sdkOutputPath)
    ->makeSDK($sdkOutputPath, false)
    ->cleanCodePHPCSFixer([$sdkOutputPath])
    ->runSDKTests($sdkOutputPath)
    ->sendSDKToGit($sdkOutputPath);
