#!/usr/bin/env php
<?php

$rootOfApp = __DIR__ . "/../../../../";

require_once($rootOfApp . "/bootstrap.php");
ini_set("memory_limit", "256M");

$scope = APP_CORE_NAME;

try {
    $databaseConfigs = $scope::Container()->get(\Segura\AppCore\DbConfig::class);
}catch(\Segura\AppCore\Exceptions\DbConfigException $dbConfigException){
    $databaseConfigs = null;
}

$zenderator = new \Zenderator\Zenderator(
    $rootOfApp,
    $databaseConfigs
);
$sdkOutputPath = isset($argv[1]) ? $argv[1] : APP_ROOT . "/vendor/segura/lib" . strtolower(APP_NAME) . "/";
$remoteApiUri = isset($argv[2]) ? $argv[2] : null;

$zenderator->runSdkifier($sdkOutputPath, $remoteApiUri);
