#!/usr/bin/env php
<?php

$rootOfApp = __DIR__ . "/../../../../";

require_once($rootOfApp . "/bootstrap.php");
$databaseConfigs = require($rootOfApp . "/config/mysql.php");
$zenderator = new \Zenderator\Zenderator(
    $rootOfApp,
    $databaseConfigs
);
$zenderator->makeZenderator();
