#!/usr/bin/env php
<?php

$rootOfApp = __DIR__ . "/../../../../";

require_once($rootOfApp . "/bootstrap.php");
ini_set("memory_limit", "256M");

$scope = APP_CORE_NAME;

try {
    $databaseConfigs = $scope::Container()->get("DatabaseConfig");
}catch(\Segura\AppCore\Exceptions\DbConfigException $dbConfigException){
    $databaseConfigs = null;
}

$zenderator = new \Zenderator\Zenderator(
    $rootOfApp,
    $databaseConfigs
);
$zenderator->makeZenderator();
