FROM php:7.2-cli
RUN apt-get update && apt-get install -y \
    libxml2 libxml2-dev \
    libpcre3-dev \
    --no-install-recommends && rm -r /var/lib/apt/lists/* && \
    pecl install xdebug-2.6.0 && \
    docker-php-ext-enable xdebug && \
    docker-php-ext-install mysqli pdo pdo_mysql soap xml json
WORKDIR /app
COPY . /app
